### ISSUE TITLE
file input fails for iron-input 2.0

### ISSUE THREAD

**Issue by two9seven** [3mp3ri0r/cpol-image#1]
file input seems to fail on upgrade of iron-input to 2.0. Any ideas why?

D

**Comment by 3mp3ri0r** [comment]
I think iron-input does not support type file. You better use regular input like in the demo instead of iron-input.

**Comment by two9seven** [comment]
Yes you are right. My problem as it turns out was with the way I was referencing the files[0] object on the input (its actually a paper-input field). Turns out I needed to fix the reference path for Polymer 2.0. See:
https://stackoverflow.com/questions/43101352/polymer-2-0-getting-paper-input-file

Thanks.

**Comment by two9seven** [comment]
closing since its not an issue with cpol-image.

**Comment by 3mp3ri0r** [comment]
Nicw to know that you use cpol-image. Thanks @two9seven.

**Comment by two9seven** [comment]
Yes thanks for making it!
